export const messages = {
  settings: "Settings",
  sourceDenied:
    "Access to this HomeBox source is unavailable. Its saved details are hidden.",
  networkDenied:
    "Access to a Network source is unavailable. Its details are hidden; rooms and documents from other sources are still available.",
  skip: "Skip to content",
  home: "Home",
  places: "Rooms & places",
  documents: "Documents & links",
  maintenance: "Maintenance",
  unplaced: "No fixed place",
  language: "Language",
  homeSelect: "Home",
  search: "Search names, models or documents",
  searchButton: "Search",
  clear: "Clear search",
  archives: "Include archived records",
  place: "Place",
  item: "Item",
  unknownType: "Type not recorded",
  room: "Room",
  floor: "Floor",
  building: "Building",
  container: "Container",
  unknown: "Not recorded",
  childPlaces: "Places inside",
  directItems: "Items here",
  nestedItems: "Items in child places",
  counts: "{0} here · {1} in child places",
  allPlaces: "All rooms & places",
  emptyPlaces: "No places recorded yet.",
  emptyItems: "No items recorded here.",
  emptyDocuments: "No documents or links recorded for this item.",
  emptyMaintenance: "No maintenance recorded for this item.",
  emptyPlaceDocuments: "No documents or links recorded for this place.",
  emptyPlaceMaintenance: "No maintenance recorded for this place.",
  noPlacePhotos: "No photos recorded for this place.",
  placeFileUnavailable:
    "This file is unavailable. The place details are still available.",
  editorHelp: "Add or correct information in HomeBox.",
  readerHelp:
    "Ask a household editor to add or correct information in HomeBox.",
  noResults: "No matches for “{0}” in this home.",
  results: "{0} matching records",
  searchTitle: "Search results",
  mobile: "Moves around; no fixed place.",
  missingPlace: "Place not recorded.",
  missingParent: "Parent place is not available in the saved information.",
  archived: "Archived in HomeBox.",
  review: "Match needs review.",
  unresolved:
    "This record could not be found in the latest check. Its previous details are saved.",
  deleted: "Confirmed deleted in HomeBox. Previous details are retained.",
  saved: "Saved from HomeBox",
  success: "Last successful update",
  sourceUpdated: "Record updated in HomeBox",
  retrieved: "Record retrieved",
  stale: "Showing older saved information from {0}.",
  unavailable: "HomeBox is unavailable. Showing saved information from {0}.",
  noCache: "HomeBox is unavailable and no saved information is available.",
  emptySource: "No saved HomeBox information yet.",
  cacheNote:
    "Saved item details do not guarantee that photos or documents are available.",
  refresh: "Check for updates",
  refreshing: "Checking for updates…",
  refreshFailed:
    "The update did not succeed. Saved information has kept its previous date.",
  expired: "Sign in again to view this home.",
  denied: "You do not have access to this home.",
  revoked: "Access to this home has been revoked.",
  signIn: "Sign in",
  loading: "Loading saved information…",
  viewUnavailable: "This home could not be loaded. Try again.",
  retry: "Try again",
  notFound: "This record is not available in this view.",
  edit: "Edit in HomeBox",
  maintenanceEdit: "Open maintenance in HomeBox",
  linkUnavailable: "A verified HomeBox link is not available.",
  photo: "Photos",
  noPhotos: "No photos recorded for this item.",
  fileUnavailable:
    "This file is unavailable. The item details are still available.",
  photoAlt: "Photo of {0}: {1}",
  storedFile: "Stored file",
  external: "External website · not archived",
  externalOpen: "Open website",
  download: "Download file",
  unknownFormat: "File type not recorded",
  scheduled: "Scheduled",
  completed: "Completed",
  unscheduled: "Date not recorded",
  due: "Scheduled for {0}",
  done: "Completed on {0}",
  cost: "Recorded cost",
  currencyUnknown: "Currency not recorded",
  description: "Description",
  manufacturer: "Manufacturer",
  model: "Model",
  serial: "Serial number",
  quantity: "Quantity",
  notes: "Notes",
  location: "Place",
  details: "Source details",
  network: "Network details",
  networkUnavailable:
    "Network details are unavailable. Rooms and document references are still available.",
  networkSaved:
    "Older Network information; this does not show whether the item is switched off.",
  networkIndependent: "Network availability does not change item placement.",
  sourceConfidence: "Source confidence",
  evidenceBasis: "Evidence basis",
  factAt: "Fact date",
  revision: "Source revision",
  vantage: "Observation point",
  snapshot: "Source snapshot",
  membership:
    "Membership of a shared network; it does not describe a cable chain.",
  historical:
    "Historical or disputed association; not a current connection or place.",
  connection: "Reported connection; physical route not recorded.",
  confirm: "confirmed",
  reported: "reported",
  inferred: "inferred",
  confidenceUnknown: "unknown",
  ownerReport: "owner report",
  observation: "observation",
  inference: "inference",
  evidenceUnknown: "unknown",
  back: "Back",
  root: "No parent place recorded",
  archivedHidden:
    "This record is archived. Include archived records to view it.",
  emptyUnplaced: "No items without a recorded place in this view.",
  unknownRecords: "Records with no recorded type",
  docOwner: "For {0}",
  homebox: "HomeBox",
  networkSource: "Network",
  unavailableLinkReference: "Reference saved; website link unavailable.",
  unavailableReference: "Reference saved; file access unavailable.",
  at: " at ",
  filter: "View options",
  noIndexDocuments: "No documents or links recorded in this home.",
  noIndexMaintenance: "No maintenance recorded in this home.",
} as const;
export type MessageKey = keyof typeof messages;
export function text(key: MessageKey, ...args: (string | number)[]): string {
  return messages[key].replace(/\{(\d+)\}/g, (_, i: string) =>
    String(args[Number(i)] ?? ""),
  );
}
export function formatDate(value: string | null | undefined): string {
  if (!value || !Number.isFinite(Date.parse(value))) return text("unknown");
  return (
    new Intl.DateTimeFormat("en-GB", {
      dateStyle: "medium",
      timeStyle: "short",
      timeZone: "UTC",
    }).format(new Date(value)) + " UTC"
  );
}
