// @generated by tools/rust-baseline/generate-contracts.mjs; do not edit.
// packages/contracts/schemas/atlas.schema.json sha256:b24f2d0ba25287ecbeb6618dd26728cb201875103edaede51804e00e26c3bc86
// packages/contracts/history/http-history.v1.1.0.schema.json sha256:bf9dd4d7894d668a271234f2db2879f302e26f32c62746d8c37784958952248a
// DTOs preserve wire shape. contracts::{decode, validate, encode} enforces schema constraints.
use super::{ConstBool, ConstInt, Contract, JsonInteger, JsonNumber, Optional, required_field};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Scope {
    #[serde(rename = "workspaceId")]
    pub workspace_id: String,
    #[serde(rename = "homeId")]
    pub home_id: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SourceKey {
    #[serde(rename = "sourceInstanceId")]
    pub source_instance_id: String,
    #[serde(rename = "collectionId")]
    pub collection_id: String,
    #[serde(rename = "sourceKind")]
    pub source_kind: SourceKeySourceKind,
    #[serde(rename = "externalId")]
    pub external_id: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SourceKeySourceKind {
    #[serde(rename = "homebox-entity")]
    HomeboxEntity,
    #[serde(rename = "network-device")]
    NetworkDevice,
    #[serde(rename = "network-group")]
    NetworkGroup,
    #[serde(rename = "network-interface")]
    NetworkInterface,
    #[serde(rename = "network-segment")]
    NetworkSegment,
    #[serde(rename = "magicplan-room")]
    MagicplanRoom,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SourceRef {
    #[serde(rename = "workspaceId")]
    pub workspace_id: String,
    #[serde(rename = "homeId")]
    pub home_id: String,
    #[serde(rename = "key")]
    pub key: SourceKey,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RecordRef {
    #[serde(rename = "recordType")]
    pub record_type: RecordRefRecordType,
    #[serde(rename = "recordId")]
    pub record_id: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RecordRefRecordType {
    #[serde(rename = "identity")]
    Identity,
    #[serde(rename = "binding")]
    Binding,
    #[serde(rename = "evidence")]
    Evidence,
    #[serde(rename = "location-semantics")]
    LocationSemantics,
    #[serde(rename = "circuit")]
    Circuit,
    #[serde(rename = "valve")]
    Valve,
    #[serde(rename = "relation")]
    Relation,
    #[serde(rename = "geometry")]
    Geometry,
    #[serde(rename = "asset")]
    Asset,
    #[serde(rename = "reconciliation")]
    Reconciliation,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Uncertainty {
    #[serde(rename = "status")]
    pub status: UncertaintyStatus,
    #[serde(rename = "explanation")]
    #[serde(deserialize_with = "required_field")]
    pub explanation: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum UncertaintyStatus {
    #[serde(rename = "supported")]
    Supported,
    #[serde(rename = "inferred")]
    Inferred,
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "disputed")]
    Disputed,
    #[serde(rename = "withdrawn")]
    Withdrawn,
    #[serde(rename = "superseded")]
    Superseded,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Endpoint {
    AtlasRecord(EndpointAtlasRecord),
    Unresolved(EndpointUnresolved),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EndpointAtlasRecord {
    #[serde(rename = "kind")]
    pub kind: EndpointAtlasRecordKind,
    #[serde(rename = "ref")]
    pub r#ref: RecordRef,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum EndpointAtlasRecordKind {
    #[serde(rename = "atlas-record")]
    AtlasRecord,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EndpointUnresolved {
    #[serde(rename = "kind")]
    pub kind: EndpointUnresolvedKind,
    #[serde(rename = "description")]
    pub description: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum EndpointUnresolvedKind {
    #[serde(rename = "unresolved")]
    Unresolved,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Provenance {
    #[serde(rename = "source")]
    #[serde(deserialize_with = "required_field")]
    pub source: Option<SourceRef>,
    #[serde(rename = "sourceRevision")]
    #[serde(deserialize_with = "required_field")]
    pub source_revision: Option<ProvenanceSourceRevision>,
    #[serde(rename = "sourceConfidence")]
    #[serde(deserialize_with = "required_field")]
    pub source_confidence: Option<String>,
    #[serde(rename = "evidenceBasis")]
    pub evidence_basis: ProvenanceEvidenceBasis,
    #[serde(rename = "factAt")]
    #[serde(deserialize_with = "required_field")]
    pub fact_at: Option<String>,
    #[serde(rename = "retrievedAt")]
    pub retrieved_at: String,
    #[serde(rename = "vantage")]
    #[serde(deserialize_with = "required_field")]
    pub vantage: Option<String>,
    #[serde(rename = "uncertainty")]
    pub uncertainty: Uncertainty,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ProvenanceSourceRevision {
    String(String),
    Integer(JsonInteger),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProvenanceEvidenceBasis {
    #[serde(rename = "owner-report")]
    OwnerReport,
    #[serde(rename = "source-report")]
    SourceReport,
    #[serde(rename = "physical-survey")]
    PhysicalSurvey,
    #[serde(rename = "document")]
    Document,
    #[serde(rename = "inference")]
    Inference,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EvidencePayload {
    #[serde(rename = "statement")]
    pub statement: String,
    #[serde(rename = "provenance")]
    pub provenance: Provenance,
    #[serde(rename = "supersedesEvidenceIds")]
    pub supersedes_evidence_ids: Vec<String>,
    #[serde(rename = "references")]
    pub references: Vec<EvidencePayloadReferencesItem>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EvidencePayloadReferencesItem {
    AtlasAsset(EvidencePayloadReferencesItemAtlasAsset),
    HomeboxAttachment(EvidencePayloadReferencesItemHomeboxAttachment),
    ExternalLink(EvidencePayloadReferencesItemExternalLink),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EvidencePayloadReferencesItemAtlasAsset {
    #[serde(rename = "kind")]
    pub kind: EvidencePayloadReferencesItemAtlasAssetKind,
    #[serde(rename = "assetId")]
    pub asset_id: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum EvidencePayloadReferencesItemAtlasAssetKind {
    #[serde(rename = "atlas-asset")]
    AtlasAsset,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EvidencePayloadReferencesItemHomeboxAttachment {
    #[serde(rename = "kind")]
    pub kind: EvidencePayloadReferencesItemHomeboxAttachmentKind,
    #[serde(rename = "entity")]
    pub entity: SourceRef,
    #[serde(rename = "attachmentId")]
    pub attachment_id: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum EvidencePayloadReferencesItemHomeboxAttachmentKind {
    #[serde(rename = "homebox-attachment")]
    HomeboxAttachment,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EvidencePayloadReferencesItemExternalLink {
    #[serde(rename = "kind")]
    pub kind: EvidencePayloadReferencesItemExternalLinkKind,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "archived")]
    pub archived: ConstBool<false>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum EvidencePayloadReferencesItemExternalLinkKind {
    #[serde(rename = "external-link")]
    ExternalLink,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct IdentityPayload {
    #[serde(rename = "kind")]
    pub kind: IdentityPayloadKind,
    #[serde(rename = "evidenceIds")]
    pub evidence_ids: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum IdentityPayloadKind {
    #[serde(rename = "location")]
    Location,
    #[serde(rename = "item")]
    Item,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BindingPayload {
    #[serde(rename = "atlasId")]
    pub atlas_id: String,
    #[serde(rename = "source")]
    pub source: SourceKey,
    #[serde(rename = "reviewStatus")]
    pub review_status: BindingPayloadReviewStatus,
    #[serde(rename = "sourceState")]
    pub source_state: BindingPayloadSourceState,
    #[serde(rename = "evidenceIds")]
    pub evidence_ids: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum BindingPayloadReviewStatus {
    #[serde(rename = "proposed")]
    Proposed,
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "retired")]
    Retired,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum BindingPayloadSourceState {
    #[serde(rename = "present")]
    Present,
    #[serde(rename = "archived")]
    Archived,
    #[serde(rename = "unresolved")]
    Unresolved,
    #[serde(rename = "confirmed-deleted")]
    ConfirmedDeleted,
    #[serde(rename = "access-revoked")]
    AccessRevoked,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LocationSemanticsPayload {
    #[serde(rename = "label")]
    #[serde(default, skip_serializing_if = "Optional::is_missing")]
    pub label: Optional<String>,
    #[serde(rename = "atlasId")]
    pub atlas_id: String,
    #[serde(rename = "semanticKind")]
    pub semantic_kind: LocationSemanticsPayloadSemanticKind,
    #[serde(rename = "reviewStatus")]
    pub review_status: LocationSemanticsPayloadReviewStatus,
    #[serde(rename = "evidenceIds")]
    pub evidence_ids: Vec<String>,
    #[serde(rename = "elevation")]
    #[serde(default, skip_serializing_if = "Optional::is_missing")]
    pub elevation: Optional<LocationElevation>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum LocationSemanticsPayloadSemanticKind {
    #[serde(rename = "unclassified")]
    Unclassified,
    #[serde(rename = "site")]
    Site,
    #[serde(rename = "building")]
    Building,
    #[serde(rename = "floor")]
    Floor,
    #[serde(rename = "room")]
    Room,
    #[serde(rename = "other")]
    Other,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum LocationSemanticsPayloadReviewStatus {
    #[serde(rename = "proposed")]
    Proposed,
    #[serde(rename = "accepted")]
    Accepted,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CircuitPayload {
    #[serde(rename = "label")]
    #[serde(deserialize_with = "required_field")]
    pub label: Option<String>,
    #[serde(rename = "panel")]
    #[serde(deserialize_with = "required_field")]
    pub panel: Option<Endpoint>,
    #[serde(rename = "evidenceIds")]
    pub evidence_ids: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ValvePayload {
    #[serde(rename = "label")]
    #[serde(deserialize_with = "required_field")]
    pub label: Option<String>,
    #[serde(rename = "medium")]
    pub medium: ValvePayloadMedium,
    #[serde(rename = "evidenceIds")]
    pub evidence_ids: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ValvePayloadMedium {
    #[serde(rename = "water")]
    Water,
    #[serde(rename = "gas")]
    Gas,
    #[serde(rename = "heating")]
    Heating,
    #[serde(rename = "other")]
    Other,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RelationPayload {
    Object(RelationPayloadObject),
    LocationMembership(RelationPayloadLocationMembership),
    PhysicalAccess(RelationPayloadPhysicalAccess),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RelationPayloadObject {
    #[serde(rename = "kind")]
    pub kind: RelationPayloadObjectKind,
    #[serde(rename = "from")]
    pub r#from: Endpoint,
    #[serde(rename = "to")]
    pub to: Endpoint,
    #[serde(rename = "medium")]
    pub medium: RelationPayloadObjectMedium,
    #[serde(rename = "uncertainty")]
    pub uncertainty: Uncertainty,
    #[serde(rename = "evidenceIds")]
    pub evidence_ids: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RelationPayloadObjectKind {
    #[serde(rename = "circuit-supplies")]
    CircuitSupplies,
    #[serde(rename = "valve-controls")]
    ValveControls,
    #[serde(rename = "documented-connection")]
    DocumentedConnection,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RelationPayloadObjectMedium {
    #[serde(rename = "electricity")]
    Electricity,
    #[serde(rename = "water")]
    Water,
    #[serde(rename = "gas")]
    Gas,
    #[serde(rename = "heating")]
    Heating,
    #[serde(rename = "ethernet")]
    Ethernet,
    #[serde(rename = "wifi")]
    Wifi,
    #[serde(rename = "other")]
    Other,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RelationPayloadLocationMembership {
    #[serde(rename = "kind")]
    pub kind: RelationPayloadLocationMembershipKind,
    #[serde(rename = "membershipKind")]
    pub membership_kind: RelationPayloadLocationMembershipMembershipKind,
    #[serde(rename = "from")]
    pub r#from: LocationEndpoint,
    #[serde(rename = "to")]
    pub to: LocationEndpoint,
    #[serde(rename = "reviewStatus")]
    pub review_status: RelationPayloadLocationMembershipReviewStatus,
    #[serde(rename = "uncertainty")]
    pub uncertainty: Uncertainty,
    #[serde(rename = "evidenceIds")]
    pub evidence_ids: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RelationPayloadLocationMembershipKind {
    #[serde(rename = "location-membership")]
    LocationMembership,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RelationPayloadLocationMembershipMembershipKind {
    #[serde(rename = "building")]
    Building,
    #[serde(rename = "level")]
    Level,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RelationPayloadLocationMembershipReviewStatus {
    #[serde(rename = "proposed")]
    Proposed,
    #[serde(rename = "accepted")]
    Accepted,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RelationPayloadPhysicalAccess {
    #[serde(rename = "kind")]
    pub kind: RelationPayloadPhysicalAccessKind,
    #[serde(rename = "accessKind")]
    pub access_kind: RelationPayloadPhysicalAccessAccessKind,
    #[serde(rename = "assertion")]
    pub assertion: RelationPayloadPhysicalAccessAssertion,
    #[serde(rename = "direction")]
    pub direction: RelationPayloadPhysicalAccessDirection,
    #[serde(rename = "from")]
    pub r#from: LocationEndpoint,
    #[serde(rename = "to")]
    pub to: LocationEndpoint,
    #[serde(rename = "reviewStatus")]
    pub review_status: RelationPayloadPhysicalAccessReviewStatus,
    #[serde(rename = "uncertainty")]
    pub uncertainty: Uncertainty,
    #[serde(rename = "evidenceIds")]
    pub evidence_ids: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RelationPayloadPhysicalAccessKind {
    #[serde(rename = "physical-access")]
    PhysicalAccess,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RelationPayloadPhysicalAccessAccessKind {
    #[serde(rename = "door")]
    Door,
    #[serde(rename = "stair")]
    Stair,
    #[serde(rename = "opening")]
    Opening,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RelationPayloadPhysicalAccessAssertion {
    #[serde(rename = "present")]
    Present,
    #[serde(rename = "absent")]
    Absent,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RelationPayloadPhysicalAccessDirection {
    #[serde(rename = "bidirectional")]
    Bidirectional,
    #[serde(rename = "from-to")]
    FromTo,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RelationPayloadPhysicalAccessReviewStatus {
    #[serde(rename = "proposed")]
    Proposed,
    #[serde(rename = "accepted")]
    Accepted,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct License {
    #[serde(rename = "status")]
    pub status: LicenseStatus,
    #[serde(rename = "reference")]
    #[serde(deserialize_with = "required_field")]
    pub reference: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum LicenseStatus {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "permitted")]
    Permitted,
    #[serde(rename = "restricted")]
    Restricted,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AssetPayload {
    #[serde(rename = "owner")]
    pub owner: AssetPayloadOwner,
    #[serde(rename = "purpose")]
    pub purpose: AssetPayloadPurpose,
    #[serde(rename = "storageKey")]
    pub storage_key: String,
    #[serde(rename = "sha256")]
    pub sha256: String,
    #[serde(rename = "byteSize")]
    pub byte_size: JsonInteger,
    #[serde(rename = "contentType")]
    pub content_type: String,
    #[serde(rename = "sourceLicense")]
    pub source_license: License,
    #[serde(rename = "availability")]
    pub availability: AssetPayloadAvailability,
    #[serde(rename = "previewPolicy")]
    pub preview_policy: AssetPayloadPreviewPolicy,
    #[serde(rename = "evidenceIds")]
    pub evidence_ids: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AssetPayloadOwner {
    #[serde(rename = "atlas")]
    Atlas,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AssetPayloadPurpose {
    #[serde(rename = "geometry-original")]
    GeometryOriginal,
    #[serde(rename = "evidence-original")]
    EvidenceOriginal,
    #[serde(rename = "derived-preview")]
    DerivedPreview,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AssetPayloadAvailability {
    #[serde(rename = "available")]
    Available,
    #[serde(rename = "missing")]
    Missing,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AssetPayloadPreviewPolicy {
    #[serde(rename = "unreviewed")]
    Unreviewed,
    #[serde(rename = "blocked")]
    Blocked,
    #[serde(rename = "safe-rendered")]
    SafeRendered,
    #[serde(rename = "download-only")]
    DownloadOnly,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GeometryPayload {
    #[serde(rename = "producer")]
    pub producer: GeometryPayloadProducer,
    #[serde(rename = "producerVersion")]
    #[serde(deserialize_with = "required_field")]
    pub producer_version: Option<String>,
    #[serde(rename = "exportFormat")]
    pub export_format: String,
    #[serde(rename = "originalAssetId")]
    pub original_asset_id: String,
    #[serde(rename = "importedAt")]
    pub imported_at: String,
    #[serde(rename = "coordinateUnits")]
    pub coordinate_units: GeometryPayloadCoordinateUnits,
    #[serde(rename = "scale")]
    #[serde(deserialize_with = "required_field")]
    pub scale: Option<JsonNumber>,
    #[serde(rename = "transform")]
    #[serde(deserialize_with = "required_field")]
    pub transform: Option<Vec<JsonNumber>>,
    #[serde(rename = "geometryVersion")]
    pub geometry_version: JsonInteger,
    #[serde(rename = "previousGeometryId")]
    #[serde(deserialize_with = "required_field")]
    pub previous_geometry_id: Option<String>,
    #[serde(rename = "mappings")]
    pub mappings: Vec<GeometryPayloadMappingsItem>,
    #[serde(rename = "evidenceIds")]
    pub evidence_ids: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum GeometryPayloadProducer {
    #[serde(rename = "magicplan")]
    Magicplan,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum GeometryPayloadCoordinateUnits {
    #[serde(rename = "mm")]
    Mm,
    #[serde(rename = "cm")]
    Cm,
    #[serde(rename = "m")]
    M,
    #[serde(rename = "in")]
    In,
    #[serde(rename = "ft")]
    Ft,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GeometryPayloadMappingsItem {
    #[serde(rename = "producerRoomId")]
    pub producer_room_id: String,
    #[serde(rename = "atlasId")]
    pub atlas_id: String,
    #[serde(rename = "homeboxEntity")]
    #[serde(deserialize_with = "required_field")]
    pub homebox_entity: Option<SourceRef>,
    #[serde(rename = "reviewStatus")]
    pub review_status: GeometryPayloadMappingsItemReviewStatus,
    #[serde(rename = "evidenceIds")]
    pub evidence_ids: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum GeometryPayloadMappingsItemReviewStatus {
    #[serde(rename = "proposed")]
    Proposed,
    #[serde(rename = "accepted")]
    Accepted,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ReconciliationPayload {
    #[serde(rename = "atlasId")]
    pub atlas_id: String,
    #[serde(rename = "fromBindingId")]
    pub from_binding_id: String,
    #[serde(rename = "toBindingId")]
    pub to_binding_id: String,
    #[serde(rename = "reason")]
    pub reason: ReconciliationPayloadReason,
    #[serde(rename = "evidenceIds")]
    pub evidence_ids: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ReconciliationPayloadReason {
    #[serde(rename = "import-id-remap")]
    ImportIdRemap,
    #[serde(rename = "source-restore")]
    SourceRestore,
    #[serde(rename = "reviewed-correction")]
    ReviewedCorrection,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct IdentityRecord {
    #[serde(rename = "schemaVersion")]
    pub schema_version: ConstInt<1>,
    #[serde(rename = "recordType")]
    pub record_type: IdentityRecordRecordType,
    #[serde(rename = "recordId")]
    pub record_id: String,
    #[serde(rename = "workspaceId")]
    pub workspace_id: String,
    #[serde(rename = "homeId")]
    pub home_id: String,
    #[serde(rename = "revision")]
    pub revision: JsonInteger,
    #[serde(rename = "lifecycle")]
    pub lifecycle: IdentityRecordLifecycle,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "lastAuditId")]
    pub last_audit_id: String,
    #[serde(rename = "payload")]
    pub payload: IdentityPayload,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum IdentityRecordRecordType {
    #[serde(rename = "identity")]
    Identity,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum IdentityRecordLifecycle {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "tombstoned")]
    Tombstoned,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BindingRecord {
    #[serde(rename = "schemaVersion")]
    pub schema_version: ConstInt<1>,
    #[serde(rename = "recordType")]
    pub record_type: BindingRecordRecordType,
    #[serde(rename = "recordId")]
    pub record_id: String,
    #[serde(rename = "workspaceId")]
    pub workspace_id: String,
    #[serde(rename = "homeId")]
    pub home_id: String,
    #[serde(rename = "revision")]
    pub revision: JsonInteger,
    #[serde(rename = "lifecycle")]
    pub lifecycle: BindingRecordLifecycle,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "lastAuditId")]
    pub last_audit_id: String,
    #[serde(rename = "payload")]
    pub payload: BindingPayload,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum BindingRecordRecordType {
    #[serde(rename = "binding")]
    Binding,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum BindingRecordLifecycle {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "tombstoned")]
    Tombstoned,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EvidenceRecord {
    #[serde(rename = "schemaVersion")]
    pub schema_version: ConstInt<1>,
    #[serde(rename = "recordType")]
    pub record_type: EvidenceRecordRecordType,
    #[serde(rename = "recordId")]
    pub record_id: String,
    #[serde(rename = "workspaceId")]
    pub workspace_id: String,
    #[serde(rename = "homeId")]
    pub home_id: String,
    #[serde(rename = "revision")]
    pub revision: JsonInteger,
    #[serde(rename = "lifecycle")]
    pub lifecycle: EvidenceRecordLifecycle,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "lastAuditId")]
    pub last_audit_id: String,
    #[serde(rename = "payload")]
    pub payload: EvidencePayload,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum EvidenceRecordRecordType {
    #[serde(rename = "evidence")]
    Evidence,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum EvidenceRecordLifecycle {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "tombstoned")]
    Tombstoned,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LocationSemanticsRecord {
    #[serde(rename = "schemaVersion")]
    pub schema_version: ConstInt<1>,
    #[serde(rename = "recordType")]
    pub record_type: LocationSemanticsRecordRecordType,
    #[serde(rename = "recordId")]
    pub record_id: String,
    #[serde(rename = "workspaceId")]
    pub workspace_id: String,
    #[serde(rename = "homeId")]
    pub home_id: String,
    #[serde(rename = "revision")]
    pub revision: JsonInteger,
    #[serde(rename = "lifecycle")]
    pub lifecycle: LocationSemanticsRecordLifecycle,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "lastAuditId")]
    pub last_audit_id: String,
    #[serde(rename = "payload")]
    pub payload: LocationSemanticsPayload,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum LocationSemanticsRecordRecordType {
    #[serde(rename = "location-semantics")]
    LocationSemantics,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum LocationSemanticsRecordLifecycle {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "tombstoned")]
    Tombstoned,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CircuitRecord {
    #[serde(rename = "schemaVersion")]
    pub schema_version: ConstInt<1>,
    #[serde(rename = "recordType")]
    pub record_type: CircuitRecordRecordType,
    #[serde(rename = "recordId")]
    pub record_id: String,
    #[serde(rename = "workspaceId")]
    pub workspace_id: String,
    #[serde(rename = "homeId")]
    pub home_id: String,
    #[serde(rename = "revision")]
    pub revision: JsonInteger,
    #[serde(rename = "lifecycle")]
    pub lifecycle: CircuitRecordLifecycle,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "lastAuditId")]
    pub last_audit_id: String,
    #[serde(rename = "payload")]
    pub payload: CircuitPayload,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CircuitRecordRecordType {
    #[serde(rename = "circuit")]
    Circuit,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CircuitRecordLifecycle {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "tombstoned")]
    Tombstoned,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ValveRecord {
    #[serde(rename = "schemaVersion")]
    pub schema_version: ConstInt<1>,
    #[serde(rename = "recordType")]
    pub record_type: ValveRecordRecordType,
    #[serde(rename = "recordId")]
    pub record_id: String,
    #[serde(rename = "workspaceId")]
    pub workspace_id: String,
    #[serde(rename = "homeId")]
    pub home_id: String,
    #[serde(rename = "revision")]
    pub revision: JsonInteger,
    #[serde(rename = "lifecycle")]
    pub lifecycle: ValveRecordLifecycle,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "lastAuditId")]
    pub last_audit_id: String,
    #[serde(rename = "payload")]
    pub payload: ValvePayload,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ValveRecordRecordType {
    #[serde(rename = "valve")]
    Valve,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ValveRecordLifecycle {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "tombstoned")]
    Tombstoned,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RelationRecord {
    #[serde(rename = "schemaVersion")]
    pub schema_version: ConstInt<1>,
    #[serde(rename = "recordType")]
    pub record_type: RelationRecordRecordType,
    #[serde(rename = "recordId")]
    pub record_id: String,
    #[serde(rename = "workspaceId")]
    pub workspace_id: String,
    #[serde(rename = "homeId")]
    pub home_id: String,
    #[serde(rename = "revision")]
    pub revision: JsonInteger,
    #[serde(rename = "lifecycle")]
    pub lifecycle: RelationRecordLifecycle,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "lastAuditId")]
    pub last_audit_id: String,
    #[serde(rename = "payload")]
    pub payload: RelationPayload,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RelationRecordRecordType {
    #[serde(rename = "relation")]
    Relation,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RelationRecordLifecycle {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "tombstoned")]
    Tombstoned,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GeometryRecord {
    #[serde(rename = "schemaVersion")]
    pub schema_version: ConstInt<1>,
    #[serde(rename = "recordType")]
    pub record_type: GeometryRecordRecordType,
    #[serde(rename = "recordId")]
    pub record_id: String,
    #[serde(rename = "workspaceId")]
    pub workspace_id: String,
    #[serde(rename = "homeId")]
    pub home_id: String,
    #[serde(rename = "revision")]
    pub revision: JsonInteger,
    #[serde(rename = "lifecycle")]
    pub lifecycle: GeometryRecordLifecycle,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "lastAuditId")]
    pub last_audit_id: String,
    #[serde(rename = "payload")]
    pub payload: GeometryPayload,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum GeometryRecordRecordType {
    #[serde(rename = "geometry")]
    Geometry,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum GeometryRecordLifecycle {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "tombstoned")]
    Tombstoned,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AssetRecord {
    #[serde(rename = "schemaVersion")]
    pub schema_version: ConstInt<1>,
    #[serde(rename = "recordType")]
    pub record_type: AssetRecordRecordType,
    #[serde(rename = "recordId")]
    pub record_id: String,
    #[serde(rename = "workspaceId")]
    pub workspace_id: String,
    #[serde(rename = "homeId")]
    pub home_id: String,
    #[serde(rename = "revision")]
    pub revision: JsonInteger,
    #[serde(rename = "lifecycle")]
    pub lifecycle: AssetRecordLifecycle,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "lastAuditId")]
    pub last_audit_id: String,
    #[serde(rename = "payload")]
    pub payload: AssetPayload,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AssetRecordRecordType {
    #[serde(rename = "asset")]
    Asset,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AssetRecordLifecycle {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "tombstoned")]
    Tombstoned,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ReconciliationRecord {
    #[serde(rename = "schemaVersion")]
    pub schema_version: ConstInt<1>,
    #[serde(rename = "recordType")]
    pub record_type: ReconciliationRecordRecordType,
    #[serde(rename = "recordId")]
    pub record_id: String,
    #[serde(rename = "workspaceId")]
    pub workspace_id: String,
    #[serde(rename = "homeId")]
    pub home_id: String,
    #[serde(rename = "revision")]
    pub revision: JsonInteger,
    #[serde(rename = "lifecycle")]
    pub lifecycle: ReconciliationRecordLifecycle,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "lastAuditId")]
    pub last_audit_id: String,
    #[serde(rename = "payload")]
    pub payload: ReconciliationPayload,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ReconciliationRecordRecordType {
    #[serde(rename = "reconciliation")]
    Reconciliation,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ReconciliationRecordLifecycle {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "tombstoned")]
    Tombstoned,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AtlasRecord {
    IdentityRecord(IdentityRecord),
    BindingRecord(BindingRecord),
    EvidenceRecord(EvidenceRecord),
    LocationSemanticsRecord(LocationSemanticsRecord),
    CircuitRecord(CircuitRecord),
    ValveRecord(ValveRecord),
    RelationRecord(RelationRecord),
    GeometryRecord(GeometryRecord),
    AssetRecord(AssetRecord),
    ReconciliationRecord(ReconciliationRecord),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Audit {
    #[serde(rename = "schemaVersion")]
    pub schema_version: ConstInt<1>,
    #[serde(rename = "auditId")]
    pub audit_id: String,
    #[serde(rename = "workspaceId")]
    pub workspace_id: String,
    #[serde(rename = "homeId")]
    pub home_id: String,
    #[serde(rename = "record")]
    pub record: RecordRef,
    #[serde(rename = "operation")]
    pub operation: AuditOperation,
    #[serde(rename = "previousRevision")]
    #[serde(deserialize_with = "required_field")]
    pub previous_revision: Option<JsonInteger>,
    #[serde(rename = "resultRevision")]
    pub result_revision: JsonInteger,
    #[serde(rename = "actorId")]
    pub actor_id: String,
    #[serde(rename = "at")]
    pub at: String,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "mutationId")]
    pub mutation_id: String,
    #[serde(rename = "beforeDigest")]
    #[serde(deserialize_with = "required_field")]
    pub before_digest: Option<String>,
    #[serde(rename = "afterDigest")]
    pub after_digest: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AuditOperation {
    #[serde(rename = "create")]
    Create,
    #[serde(rename = "replace")]
    Replace,
    #[serde(rename = "tombstone")]
    Tombstone,
    #[serde(rename = "restore")]
    Restore,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Guard {
    #[serde(rename = "record")]
    pub record: RecordRef,
    #[serde(rename = "expectedRevision")]
    pub expected_revision: JsonInteger,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Mutation {
    Create(MutationCreate),
    Replace(MutationReplace),
    Tombstone(MutationTombstone),
    Restore(MutationRestore),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MutationCreate {
    #[serde(rename = "schemaVersion")]
    pub schema_version: ConstInt<1>,
    #[serde(rename = "mutationId")]
    pub mutation_id: String,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "guards")]
    pub guards: Vec<Guard>,
    #[serde(rename = "operation")]
    pub operation: MutationCreateOperation,
    #[serde(rename = "expectedRevision")]
    #[serde(deserialize_with = "required_field")]
    pub expected_revision: (),
    #[serde(rename = "value")]
    pub value: RecordValue,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MutationCreateOperation {
    #[serde(rename = "create")]
    Create,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MutationReplace {
    #[serde(rename = "schemaVersion")]
    pub schema_version: ConstInt<1>,
    #[serde(rename = "mutationId")]
    pub mutation_id: String,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "guards")]
    pub guards: Vec<Guard>,
    #[serde(rename = "operation")]
    pub operation: MutationReplaceOperation,
    #[serde(rename = "expectedRevision")]
    pub expected_revision: JsonInteger,
    #[serde(rename = "value")]
    pub value: RecordValue,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MutationReplaceOperation {
    #[serde(rename = "replace")]
    Replace,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MutationTombstone {
    #[serde(rename = "schemaVersion")]
    pub schema_version: ConstInt<1>,
    #[serde(rename = "mutationId")]
    pub mutation_id: String,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "guards")]
    pub guards: Vec<Guard>,
    #[serde(rename = "operation")]
    pub operation: MutationTombstoneOperation,
    #[serde(rename = "expectedRevision")]
    pub expected_revision: JsonInteger,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MutationTombstoneOperation {
    #[serde(rename = "tombstone")]
    Tombstone,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MutationRestore {
    #[serde(rename = "schemaVersion")]
    pub schema_version: ConstInt<1>,
    #[serde(rename = "mutationId")]
    pub mutation_id: String,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "guards")]
    pub guards: Vec<Guard>,
    #[serde(rename = "operation")]
    pub operation: MutationRestoreOperation,
    #[serde(rename = "expectedRevision")]
    pub expected_revision: JsonInteger,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MutationRestoreOperation {
    #[serde(rename = "restore")]
    Restore,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RecordValue {
    Identity(RecordValueIdentity),
    Binding(RecordValueBinding),
    Evidence(RecordValueEvidence),
    LocationSemantics(RecordValueLocationSemantics),
    Circuit(RecordValueCircuit),
    Valve(RecordValueValve),
    Relation(RecordValueRelation),
    Geometry(RecordValueGeometry),
    Asset(RecordValueAsset),
    Reconciliation(RecordValueReconciliation),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RecordValueIdentity {
    #[serde(rename = "recordType")]
    pub record_type: RecordValueIdentityRecordType,
    #[serde(rename = "payload")]
    pub payload: IdentityPayload,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RecordValueIdentityRecordType {
    #[serde(rename = "identity")]
    Identity,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RecordValueBinding {
    #[serde(rename = "recordType")]
    pub record_type: RecordValueBindingRecordType,
    #[serde(rename = "payload")]
    pub payload: BindingPayload,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RecordValueBindingRecordType {
    #[serde(rename = "binding")]
    Binding,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RecordValueEvidence {
    #[serde(rename = "recordType")]
    pub record_type: RecordValueEvidenceRecordType,
    #[serde(rename = "payload")]
    pub payload: EvidencePayload,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RecordValueEvidenceRecordType {
    #[serde(rename = "evidence")]
    Evidence,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RecordValueLocationSemantics {
    #[serde(rename = "recordType")]
    pub record_type: RecordValueLocationSemanticsRecordType,
    #[serde(rename = "payload")]
    pub payload: LocationSemanticsPayload,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RecordValueLocationSemanticsRecordType {
    #[serde(rename = "location-semantics")]
    LocationSemantics,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RecordValueCircuit {
    #[serde(rename = "recordType")]
    pub record_type: RecordValueCircuitRecordType,
    #[serde(rename = "payload")]
    pub payload: CircuitPayload,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RecordValueCircuitRecordType {
    #[serde(rename = "circuit")]
    Circuit,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RecordValueValve {
    #[serde(rename = "recordType")]
    pub record_type: RecordValueValveRecordType,
    #[serde(rename = "payload")]
    pub payload: ValvePayload,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RecordValueValveRecordType {
    #[serde(rename = "valve")]
    Valve,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RecordValueRelation {
    #[serde(rename = "recordType")]
    pub record_type: RecordValueRelationRecordType,
    #[serde(rename = "payload")]
    pub payload: RelationPayload,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RecordValueRelationRecordType {
    #[serde(rename = "relation")]
    Relation,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RecordValueGeometry {
    #[serde(rename = "recordType")]
    pub record_type: RecordValueGeometryRecordType,
    #[serde(rename = "payload")]
    pub payload: GeometryPayload,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RecordValueGeometryRecordType {
    #[serde(rename = "geometry")]
    Geometry,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RecordValueAsset {
    #[serde(rename = "recordType")]
    pub record_type: RecordValueAssetRecordType,
    #[serde(rename = "payload")]
    pub payload: AssetPayload,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RecordValueAssetRecordType {
    #[serde(rename = "asset")]
    Asset,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RecordValueReconciliation {
    #[serde(rename = "recordType")]
    pub record_type: RecordValueReconciliationRecordType,
    #[serde(rename = "payload")]
    pub payload: ReconciliationPayload,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RecordValueReconciliationRecordType {
    #[serde(rename = "reconciliation")]
    Reconciliation,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MutationResult {
    #[serde(rename = "schemaVersion")]
    pub schema_version: ConstInt<1>,
    #[serde(rename = "record")]
    pub record: AtlasRecord,
    #[serde(rename = "audit")]
    pub audit: Audit,
    #[serde(rename = "replayed")]
    pub replayed: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ApiError {
    #[serde(rename = "schemaVersion")]
    pub schema_version: ConstInt<1>,
    #[serde(rename = "code")]
    pub code: ApiErrorCode,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "requestId")]
    pub request_id: String,
    #[serde(rename = "currentRevision")]
    #[serde(deserialize_with = "required_field")]
    pub current_revision: Option<JsonInteger>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ApiErrorCode {
    #[serde(rename = "unauthenticated")]
    Unauthenticated,
    #[serde(rename = "forbidden")]
    Forbidden,
    #[serde(rename = "not-found")]
    NotFound,
    #[serde(rename = "invalid-contract")]
    InvalidContract,
    #[serde(rename = "revision-required")]
    RevisionRequired,
    #[serde(rename = "revision-conflict")]
    RevisionConflict,
    #[serde(rename = "guard-conflict")]
    GuardConflict,
    #[serde(rename = "identity-conflict")]
    IdentityConflict,
    #[serde(rename = "idempotency-conflict")]
    IdempotencyConflict,
    #[serde(rename = "invalid-transition")]
    InvalidTransition,
    #[serde(rename = "upstream-unavailable")]
    UpstreamUnavailable,
    #[serde(rename = "upstream-incomplete")]
    UpstreamIncomplete,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Link {
    #[serde(rename = "kind")]
    pub kind: LinkKind,
    #[serde(rename = "intent")]
    pub intent: LinkIntent,
    #[serde(rename = "entity")]
    pub entity: SourceRef,
    #[serde(rename = "href")]
    pub href: String,
    #[serde(rename = "verifiedRoute")]
    pub verified_route: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum LinkKind {
    #[serde(rename = "homebox-native")]
    HomeboxNative,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum LinkIntent {
    #[serde(rename = "view")]
    View,
    #[serde(rename = "edit")]
    Edit,
    #[serde(rename = "maintenance")]
    Maintenance,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HomeboxEntityType {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "isLocation")]
    pub is_location: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Attachment {
    StoredFile(AttachmentStoredFile),
    ExternalLink(AttachmentExternalLink),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AttachmentStoredFile {
    #[serde(rename = "attachmentId")]
    pub attachment_id: String,
    #[serde(rename = "kind")]
    pub kind: AttachmentStoredFileKind,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "contentType")]
    #[serde(deserialize_with = "required_field")]
    pub content_type: Option<String>,
    #[serde(rename = "byteSize")]
    #[serde(deserialize_with = "required_field")]
    pub byte_size: Option<JsonInteger>,
    #[serde(rename = "proxyRef")]
    #[serde(deserialize_with = "required_field")]
    pub proxy_ref: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AttachmentStoredFileKind {
    #[serde(rename = "stored-file")]
    StoredFile,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AttachmentExternalLink {
    #[serde(rename = "attachmentId")]
    pub attachment_id: String,
    #[serde(rename = "kind")]
    pub kind: AttachmentExternalLinkKind,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "archived")]
    pub archived: ConstBool<false>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AttachmentExternalLinkKind {
    #[serde(rename = "external-link")]
    ExternalLink,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Maintenance {
    #[serde(rename = "entryId")]
    pub entry_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "scheduledDate")]
    #[serde(deserialize_with = "required_field")]
    pub scheduled_date: Option<String>,
    #[serde(rename = "completedDate")]
    #[serde(deserialize_with = "required_field")]
    pub completed_date: Option<String>,
    #[serde(rename = "cost")]
    #[serde(deserialize_with = "required_field")]
    pub cost: Option<JsonNumber>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HomeboxProjection {
    #[serde(rename = "schemaVersion")]
    pub schema_version: ConstInt<1>,
    #[serde(rename = "workspaceId")]
    pub workspace_id: String,
    #[serde(rename = "homeId")]
    pub home_id: String,
    #[serde(rename = "source")]
    pub source: SourceKey,
    #[serde(rename = "sourceUpdatedAt")]
    #[serde(deserialize_with = "required_field")]
    pub source_updated_at: Option<String>,
    #[serde(rename = "retrievedAt")]
    pub retrieved_at: String,
    #[serde(rename = "entity")]
    pub entity: HomeboxProjectionEntity,
    #[serde(rename = "attachments")]
    pub attachments: Vec<Attachment>,
    #[serde(rename = "maintenance")]
    pub maintenance: Vec<Maintenance>,
    #[serde(rename = "nativeLinks")]
    pub native_links: Vec<Link>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HomeboxProjectionEntity {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "entityType")]
    #[serde(deserialize_with = "required_field")]
    pub entity_type: Option<HomeboxEntityType>,
    #[serde(rename = "parent")]
    #[serde(deserialize_with = "required_field")]
    pub parent: Option<HomeboxProjectionEntityParent>,
    #[serde(rename = "archived")]
    pub archived: bool,
    #[serde(rename = "quantity")]
    #[serde(deserialize_with = "required_field")]
    pub quantity: Option<JsonNumber>,
    #[serde(rename = "manufacturer")]
    #[serde(deserialize_with = "required_field")]
    pub manufacturer: Option<String>,
    #[serde(rename = "modelNumber")]
    #[serde(deserialize_with = "required_field")]
    pub model_number: Option<String>,
    #[serde(rename = "serialNumber")]
    #[serde(deserialize_with = "required_field")]
    pub serial_number: Option<String>,
    #[serde(rename = "notes")]
    #[serde(deserialize_with = "required_field")]
    pub notes: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HomeboxProjectionEntityParent {
    #[serde(rename = "id")]
    pub id: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CacheStatus {
    #[serde(rename = "schemaVersion")]
    pub schema_version: ConstInt<1>,
    #[serde(rename = "workspaceId")]
    pub workspace_id: String,
    #[serde(rename = "homeId")]
    pub home_id: String,
    #[serde(rename = "sourceInstanceId")]
    pub source_instance_id: String,
    #[serde(rename = "collectionId")]
    pub collection_id: String,
    #[serde(rename = "status")]
    pub status: CacheStatusStatus,
    #[serde(rename = "lastSuccessfulFetchAt")]
    #[serde(deserialize_with = "required_field")]
    pub last_successful_fetch_at: Option<String>,
    #[serde(rename = "lastAttemptAt")]
    #[serde(deserialize_with = "required_field")]
    pub last_attempt_at: Option<String>,
    #[serde(rename = "generationId")]
    #[serde(deserialize_with = "required_field")]
    pub generation_id: Option<String>,
    #[serde(rename = "consistency")]
    pub consistency: CacheStatusConsistency,
    #[serde(rename = "error")]
    #[serde(deserialize_with = "required_field")]
    pub error: Option<CacheStatusError>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CacheStatusStatus {
    #[serde(rename = "empty")]
    Empty,
    #[serde(rename = "fresh")]
    Fresh,
    #[serde(rename = "stale")]
    Stale,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "access-revoked")]
    AccessRevoked,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CacheStatusConsistency {
    #[serde(rename = "non-transactional-offset-pages")]
    NonTransactionalOffsetPages,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CacheStatusError {
    #[serde(rename = "code")]
    pub code: CacheStatusErrorCode,
    #[serde(rename = "at")]
    pub at: String,
    #[serde(rename = "message")]
    pub message: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CacheStatusErrorCode {
    #[serde(rename = "timeout")]
    Timeout,
    #[serde(rename = "auth")]
    Auth,
    #[serde(rename = "wrong-scope")]
    WrongScope,
    #[serde(rename = "invalid-schema")]
    InvalidSchema,
    #[serde(rename = "pagination")]
    Pagination,
    #[serde(rename = "size-limit")]
    SizeLimit,
    #[serde(rename = "transport")]
    Transport,
    #[serde(rename = "upstream")]
    Upstream,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SourceRegistration {
    #[serde(rename = "workspaceId")]
    pub workspace_id: String,
    #[serde(rename = "homeId")]
    pub home_id: String,
    #[serde(rename = "sourceInstanceId")]
    pub source_instance_id: String,
    #[serde(rename = "collectionId")]
    pub collection_id: String,
    #[serde(rename = "owner")]
    pub owner: SourceRegistrationOwner,
    #[serde(rename = "partitionMode")]
    pub partition_mode: SourceRegistrationPartitionMode,
    #[serde(rename = "allowedExternalIds")]
    pub allowed_external_ids: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SourceRegistrationOwner {
    #[serde(rename = "homebox")]
    Homebox,
    #[serde(rename = "network")]
    Network,
    #[serde(rename = "magicplan")]
    Magicplan,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SourceRegistrationPartitionMode {
    #[serde(rename = "exclusive-home")]
    ExclusiveHome,
    #[serde(rename = "reviewed-entity-allowlist")]
    ReviewedEntityAllowlist,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NetworkEndpoint {
    #[serde(rename = "kind")]
    pub kind: NetworkEndpointKind,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "required_field")]
    pub id: Option<String>,
    #[serde(rename = "description")]
    #[serde(deserialize_with = "required_field")]
    pub description: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum NetworkEndpointKind {
    #[serde(rename = "device")]
    Device,
    #[serde(rename = "interface")]
    Interface,
    #[serde(rename = "segment")]
    Segment,
    #[serde(rename = "unresolved")]
    Unresolved,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NetworkRelation {
    #[serde(rename = "schemaVersion")]
    pub schema_version: ConstInt<1>,
    #[serde(rename = "workspaceId")]
    pub workspace_id: String,
    #[serde(rename = "homeId")]
    pub home_id: String,
    #[serde(rename = "sourceInstanceId")]
    pub source_instance_id: String,
    #[serde(rename = "collectionId")]
    pub collection_id: String,
    #[serde(rename = "externalId")]
    pub external_id: String,
    #[serde(rename = "kind")]
    pub kind: NetworkRelationKind,
    #[serde(rename = "from")]
    pub r#from: NetworkEndpoint,
    #[serde(rename = "to")]
    pub to: NetworkEndpoint,
    #[serde(rename = "medium")]
    pub medium: NetworkRelationMedium,
    #[serde(rename = "sourceRevision")]
    #[serde(deserialize_with = "required_field")]
    pub source_revision: Option<JsonInteger>,
    #[serde(rename = "sourceSnapshotAt")]
    #[serde(deserialize_with = "required_field")]
    pub source_snapshot_at: Option<String>,
    #[serde(rename = "retrievedAt")]
    pub retrieved_at: String,
    #[serde(rename = "vantage")]
    #[serde(deserialize_with = "required_field")]
    pub vantage: Option<String>,
    #[serde(rename = "sourceConfidence")]
    pub source_confidence: String,
    #[serde(rename = "evidenceBasis")]
    pub evidence_basis: NetworkRelationEvidenceBasis,
    #[serde(rename = "temporalStatus")]
    pub temporal_status: NetworkRelationTemporalStatus,
    #[serde(rename = "factAt")]
    #[serde(deserialize_with = "required_field")]
    pub fact_at: Option<String>,
    #[serde(rename = "notes")]
    pub notes: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum NetworkRelationKind {
    #[serde(rename = "network-connection")]
    NetworkConnection,
    #[serde(rename = "network-segment-membership")]
    NetworkSegmentMembership,
    #[serde(rename = "network-association")]
    NetworkAssociation,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum NetworkRelationMedium {
    #[serde(rename = "ethernet")]
    Ethernet,
    #[serde(rename = "wifi")]
    Wifi,
    #[serde(rename = "powerline")]
    Powerline,
    #[serde(rename = "wan")]
    Wan,
    #[serde(rename = "other")]
    Other,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum NetworkRelationEvidenceBasis {
    #[serde(rename = "owner-report")]
    OwnerReport,
    #[serde(rename = "source-report")]
    SourceReport,
    #[serde(rename = "physical-survey")]
    PhysicalSurvey,
    #[serde(rename = "inference")]
    Inference,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum NetworkRelationTemporalStatus {
    #[serde(rename = "current-claim")]
    CurrentClaim,
    #[serde(rename = "historical")]
    Historical,
    #[serde(rename = "withdrawn")]
    Withdrawn,
    #[serde(rename = "disputed")]
    Disputed,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Snapshot {
    #[serde(rename = "contractVersion")]
    pub contract_version: SnapshotContractVersion,
    #[serde(rename = "synthetic")]
    pub synthetic: ConstBool<true>,
    #[serde(rename = "sources")]
    pub sources: Vec<SourceRegistration>,
    #[serde(rename = "records")]
    pub records: Vec<AtlasRecord>,
    #[serde(rename = "homeboxEntities")]
    pub homebox_entities: Vec<HomeboxProjection>,
    #[serde(rename = "caches")]
    pub caches: Vec<CacheStatus>,
    #[serde(rename = "networkRelations")]
    pub network_relations: Vec<NetworkRelation>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SnapshotContractVersion {
    #[serde(rename = "1.0.0")]
    V100,
    #[serde(rename = "1.1.0")]
    V110,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct HomeboxPageWire {
    #[serde(rename = "items")]
    pub items: Vec<HomeboxPageWireItemsItem>,
    #[serde(rename = "page")]
    pub page: JsonInteger,
    #[serde(rename = "pageSize")]
    pub page_size: JsonInteger,
    #[serde(rename = "total")]
    pub total: JsonInteger,
    /// Unmodeled fields are permitted only by this open upstream wire schema.
    #[serde(flatten, serialize_with = "serialize_homebox_page_wire_extras")]
    pub additional_properties: std::collections::BTreeMap<String, serde_json::Value>,
}

impl<'de> Deserialize<'de> for HomeboxPageWire {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let mut fields = super::json_value::deserialize_fields(deserializer)?;
        Ok(Self {
            items: super::json_value::take_required(&mut fields, "items")
                .map_err(serde::de::Error::custom)?,
            page: super::json_value::take_required(&mut fields, "page")
                .map_err(serde::de::Error::custom)?,
            page_size: super::json_value::take_required(&mut fields, "pageSize")
                .map_err(serde::de::Error::custom)?,
            total: super::json_value::take_required(&mut fields, "total")
                .map_err(serde::de::Error::custom)?,
            additional_properties: super::json_value::remaining_fields(fields)
                .map_err(serde::de::Error::custom)?,
        })
    }
}

fn serialize_homebox_page_wire_extras<S: serde::Serializer>(
    properties: &std::collections::BTreeMap<String, serde_json::Value>,
    serializer: S,
) -> Result<S::Ok, S::Error> {
    super::serialize_additional_properties(
        properties,
        &["items", "page", "pageSize", "total"],
        serializer,
    )
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct HomeboxPageWireItemsItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "archived")]
    pub archived: bool,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "entityType")]
    #[serde(default, skip_serializing_if = "Optional::is_missing")]
    pub entity_type: Optional<Option<HomeboxPageWireItemsItemEntityType>>,
    #[serde(rename = "parent")]
    #[serde(default, skip_serializing_if = "Optional::is_missing")]
    pub parent: Optional<Option<HomeboxPageWireItemsItemParent>>,
    /// Unmodeled fields are permitted only by this open upstream wire schema.
    #[serde(
        flatten,
        serialize_with = "serialize_homebox_page_wire_items_item_extras"
    )]
    pub additional_properties: std::collections::BTreeMap<String, serde_json::Value>,
}

impl<'de> Deserialize<'de> for HomeboxPageWireItemsItem {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let mut fields = super::json_value::deserialize_fields(deserializer)?;
        Ok(Self {
            id: super::json_value::take_required(&mut fields, "id")
                .map_err(serde::de::Error::custom)?,
            name: super::json_value::take_required(&mut fields, "name")
                .map_err(serde::de::Error::custom)?,
            archived: super::json_value::take_required(&mut fields, "archived")
                .map_err(serde::de::Error::custom)?,
            updated_at: super::json_value::take_required(&mut fields, "updatedAt")
                .map_err(serde::de::Error::custom)?,
            entity_type: super::json_value::take_optional(&mut fields, "entityType")
                .map_err(serde::de::Error::custom)?,
            parent: super::json_value::take_optional(&mut fields, "parent")
                .map_err(serde::de::Error::custom)?,
            additional_properties: super::json_value::remaining_fields(fields)
                .map_err(serde::de::Error::custom)?,
        })
    }
}

fn serialize_homebox_page_wire_items_item_extras<S: serde::Serializer>(
    properties: &std::collections::BTreeMap<String, serde_json::Value>,
    serializer: S,
) -> Result<S::Ok, S::Error> {
    super::serialize_additional_properties(
        properties,
        &[
            "id",
            "name",
            "archived",
            "updatedAt",
            "entityType",
            "parent",
        ],
        serializer,
    )
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct HomeboxPageWireItemsItemEntityType {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "isLocation")]
    pub is_location: bool,
    /// Unmodeled fields are permitted only by this open upstream wire schema.
    #[serde(
        flatten,
        serialize_with = "serialize_homebox_page_wire_items_item_entity_type_extras"
    )]
    pub additional_properties: std::collections::BTreeMap<String, serde_json::Value>,
}

impl<'de> Deserialize<'de> for HomeboxPageWireItemsItemEntityType {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let mut fields = super::json_value::deserialize_fields(deserializer)?;
        Ok(Self {
            id: super::json_value::take_required(&mut fields, "id")
                .map_err(serde::de::Error::custom)?,
            name: super::json_value::take_required(&mut fields, "name")
                .map_err(serde::de::Error::custom)?,
            is_location: super::json_value::take_required(&mut fields, "isLocation")
                .map_err(serde::de::Error::custom)?,
            additional_properties: super::json_value::remaining_fields(fields)
                .map_err(serde::de::Error::custom)?,
        })
    }
}

fn serialize_homebox_page_wire_items_item_entity_type_extras<S: serde::Serializer>(
    properties: &std::collections::BTreeMap<String, serde_json::Value>,
    serializer: S,
) -> Result<S::Ok, S::Error> {
    super::serialize_additional_properties(properties, &["id", "name", "isLocation"], serializer)
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct HomeboxPageWireItemsItemParent {
    #[serde(rename = "id")]
    pub id: String,
    /// Unmodeled fields are permitted only by this open upstream wire schema.
    #[serde(
        flatten,
        serialize_with = "serialize_homebox_page_wire_items_item_parent_extras"
    )]
    pub additional_properties: std::collections::BTreeMap<String, serde_json::Value>,
}

impl<'de> Deserialize<'de> for HomeboxPageWireItemsItemParent {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let mut fields = super::json_value::deserialize_fields(deserializer)?;
        Ok(Self {
            id: super::json_value::take_required(&mut fields, "id")
                .map_err(serde::de::Error::custom)?,
            additional_properties: super::json_value::remaining_fields(fields)
                .map_err(serde::de::Error::custom)?,
        })
    }
}

fn serialize_homebox_page_wire_items_item_parent_extras<S: serde::Serializer>(
    properties: &std::collections::BTreeMap<String, serde_json::Value>,
    serializer: S,
) -> Result<S::Ok, S::Error> {
    super::serialize_additional_properties(properties, &["id"], serializer)
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BatchMutation {
    #[serde(rename = "schemaVersion")]
    pub schema_version: ConstInt<1>,
    #[serde(rename = "batchId")]
    pub batch_id: String,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "commands")]
    pub commands: Vec<BatchMutationCommandsItem>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BatchMutationCommandsItem {
    #[serde(rename = "target")]
    pub target: RecordRef,
    #[serde(rename = "command")]
    pub command: Mutation,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BatchResult {
    #[serde(rename = "schemaVersion")]
    pub schema_version: ConstInt<1>,
    #[serde(rename = "batchId")]
    pub batch_id: String,
    #[serde(rename = "results")]
    pub results: Vec<MutationResult>,
    #[serde(rename = "replayed")]
    pub replayed: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LocationElevation {
    Unknown(LocationElevationUnknown),
    Known(LocationElevationKnown),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LocationElevationUnknown {
    #[serde(rename = "status")]
    pub status: LocationElevationUnknownStatus,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum LocationElevationUnknownStatus {
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LocationElevationKnown {
    #[serde(rename = "status")]
    pub status: LocationElevationKnownStatus,
    #[serde(rename = "metres")]
    pub metres: JsonNumber,
    #[serde(rename = "datumAtlasId")]
    pub datum_atlas_id: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum LocationElevationKnownStatus {
    #[serde(rename = "known")]
    Known,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LocationEndpoint {
    #[serde(rename = "kind")]
    pub kind: LocationEndpointKind,
    #[serde(rename = "ref")]
    pub r#ref: LocationEndpointRef,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum LocationEndpointKind {
    #[serde(rename = "atlas-record")]
    AtlasRecord,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LocationEndpointRef {
    #[serde(rename = "recordType")]
    pub record_type: LocationEndpointRefRecordType,
    #[serde(rename = "recordId")]
    pub record_id: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum LocationEndpointRefRecordType {
    #[serde(rename = "identity")]
    Identity,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AtlasDocument {
    AtlasRecord(Box<AtlasRecord>),
    Snapshot(Box<Snapshot>),
    Mutation(Box<Mutation>),
    MutationResult(Box<MutationResult>),
    ApiError(Box<ApiError>),
}

pub type Record = AtlasRecord;
pub type HttpHistory = Vec<Audit>;

pub(crate) const SCHEMA_DEFINITIONS: &[&str] = &[
    "scope",
    "sourceKey",
    "sourceRef",
    "recordRef",
    "uncertainty",
    "endpoint",
    "provenance",
    "evidencePayload",
    "identityPayload",
    "bindingPayload",
    "locationSemanticsPayload",
    "circuitPayload",
    "valvePayload",
    "relationPayload",
    "license",
    "assetPayload",
    "geometryPayload",
    "reconciliationPayload",
    "identityRecord",
    "bindingRecord",
    "evidenceRecord",
    "location-semanticsRecord",
    "circuitRecord",
    "valveRecord",
    "relationRecord",
    "geometryRecord",
    "assetRecord",
    "reconciliationRecord",
    "record",
    "audit",
    "guard",
    "mutation",
    "recordValue",
    "mutationResult",
    "apiError",
    "link",
    "homeboxEntityType",
    "attachment",
    "maintenance",
    "homeboxProjection",
    "cacheStatus",
    "sourceRegistration",
    "networkEndpoint",
    "networkRelation",
    "snapshot",
    "homeboxPageWire",
    "batchMutation",
    "batchResult",
    "locationElevation",
    "locationEndpoint",
];

impl Contract for Scope {
    const SCHEMA_KEY: &'static str = "scope";
}
impl Contract for SourceKey {
    const SCHEMA_KEY: &'static str = "sourceKey";
}
impl Contract for SourceRef {
    const SCHEMA_KEY: &'static str = "sourceRef";
}
impl Contract for RecordRef {
    const SCHEMA_KEY: &'static str = "recordRef";
}
impl Contract for Uncertainty {
    const SCHEMA_KEY: &'static str = "uncertainty";
}
impl Contract for Endpoint {
    const SCHEMA_KEY: &'static str = "endpoint";
}
impl Contract for Provenance {
    const SCHEMA_KEY: &'static str = "provenance";
}
impl Contract for EvidencePayload {
    const SCHEMA_KEY: &'static str = "evidencePayload";
}
impl Contract for IdentityPayload {
    const SCHEMA_KEY: &'static str = "identityPayload";
}
impl Contract for BindingPayload {
    const SCHEMA_KEY: &'static str = "bindingPayload";
}
impl Contract for LocationSemanticsPayload {
    const SCHEMA_KEY: &'static str = "locationSemanticsPayload";
}
impl Contract for CircuitPayload {
    const SCHEMA_KEY: &'static str = "circuitPayload";
}
impl Contract for ValvePayload {
    const SCHEMA_KEY: &'static str = "valvePayload";
}
impl Contract for RelationPayload {
    const SCHEMA_KEY: &'static str = "relationPayload";
}
impl Contract for License {
    const SCHEMA_KEY: &'static str = "license";
}
impl Contract for AssetPayload {
    const SCHEMA_KEY: &'static str = "assetPayload";
}
impl Contract for GeometryPayload {
    const SCHEMA_KEY: &'static str = "geometryPayload";
}
impl Contract for ReconciliationPayload {
    const SCHEMA_KEY: &'static str = "reconciliationPayload";
}
impl Contract for IdentityRecord {
    const SCHEMA_KEY: &'static str = "identityRecord";
}
impl Contract for BindingRecord {
    const SCHEMA_KEY: &'static str = "bindingRecord";
}
impl Contract for EvidenceRecord {
    const SCHEMA_KEY: &'static str = "evidenceRecord";
}
impl Contract for LocationSemanticsRecord {
    const SCHEMA_KEY: &'static str = "location-semanticsRecord";
}
impl Contract for CircuitRecord {
    const SCHEMA_KEY: &'static str = "circuitRecord";
}
impl Contract for ValveRecord {
    const SCHEMA_KEY: &'static str = "valveRecord";
}
impl Contract for RelationRecord {
    const SCHEMA_KEY: &'static str = "relationRecord";
}
impl Contract for GeometryRecord {
    const SCHEMA_KEY: &'static str = "geometryRecord";
}
impl Contract for AssetRecord {
    const SCHEMA_KEY: &'static str = "assetRecord";
}
impl Contract for ReconciliationRecord {
    const SCHEMA_KEY: &'static str = "reconciliationRecord";
}
impl Contract for AtlasRecord {
    const SCHEMA_KEY: &'static str = "record";
}
impl Contract for Audit {
    const SCHEMA_KEY: &'static str = "audit";
}
impl Contract for Guard {
    const SCHEMA_KEY: &'static str = "guard";
}
impl Contract for Mutation {
    const SCHEMA_KEY: &'static str = "mutation";
}
impl Contract for RecordValue {
    const SCHEMA_KEY: &'static str = "recordValue";
}
impl Contract for MutationResult {
    const SCHEMA_KEY: &'static str = "mutationResult";
}
impl Contract for ApiError {
    const SCHEMA_KEY: &'static str = "apiError";
}
impl Contract for Link {
    const SCHEMA_KEY: &'static str = "link";
}
impl Contract for HomeboxEntityType {
    const SCHEMA_KEY: &'static str = "homeboxEntityType";
}
impl Contract for Attachment {
    const SCHEMA_KEY: &'static str = "attachment";
}
impl Contract for Maintenance {
    const SCHEMA_KEY: &'static str = "maintenance";
}
impl Contract for HomeboxProjection {
    const SCHEMA_KEY: &'static str = "homeboxProjection";
}
impl Contract for CacheStatus {
    const SCHEMA_KEY: &'static str = "cacheStatus";
}
impl Contract for SourceRegistration {
    const SCHEMA_KEY: &'static str = "sourceRegistration";
}
impl Contract for NetworkEndpoint {
    const SCHEMA_KEY: &'static str = "networkEndpoint";
}
impl Contract for NetworkRelation {
    const SCHEMA_KEY: &'static str = "networkRelation";
}
impl Contract for Snapshot {
    const SCHEMA_KEY: &'static str = "snapshot";
}
impl Contract for HomeboxPageWire {
    const SCHEMA_KEY: &'static str = "homeboxPageWire";
}
impl Contract for BatchMutation {
    const SCHEMA_KEY: &'static str = "batchMutation";
}
impl Contract for BatchResult {
    const SCHEMA_KEY: &'static str = "batchResult";
}
impl Contract for LocationElevation {
    const SCHEMA_KEY: &'static str = "locationElevation";
}
impl Contract for LocationEndpoint {
    const SCHEMA_KEY: &'static str = "locationEndpoint";
}
impl Contract for AtlasDocument {
    const SCHEMA_KEY: &'static str = "$atlas";
}
impl Contract for HttpHistory {
    const SCHEMA_KEY: &'static str = "$history";
}
