import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHomeBoxAdapter, cacheFreshness, HOMEBOX_REFERENCE_VERSION } from '../src/index.mjs';
const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url)));
const fixture = JSON.parse(readFileSync(new URL('../fixtures/catalog.json', import.meta.url)));
assert.equal(pkg.exports['.'], './src/index.mjs');
assert.equal(fixture.homeboxReferenceVersion, HOMEBOX_REFERENCE_VERSION);
assert.equal(fixture.liveProviderQualified, false);
const metadata = JSON.parse(readFileSync(new URL('../fixtures/metadata.normalized-synthetic-v1.json', import.meta.url)));
assert.equal(metadata.metadataDialect, fixture.metadataDialect);
assert.equal(metadata.liveProviderQualified, false);
assert.equal(metadata.synthetic, true);
assert.ok(metadata.entities.length);
assert.ok(metadata.entities.every(e => Array.isArray(e.attachments)));
assert.ok(Array.isArray(metadata.maintenance));
assert.equal(typeof createHomeBoxAdapter, 'function'); assert.equal(typeof cacheFreshness, 'function');
const source = readFileSync(new URL('../src/index.mjs', import.meta.url), 'utf8');
assert.ok(!/\bfetch\s*\(|https?\.request|process\.env/.test(source));
assert.ok(!/method:\s*['"](?:POST|PUT|PATCH|DELETE)['"]/.test(source));
console.log('AT-08 ES module/package/synthetic fixture and GET-only static checks pass');
